"""vendor credits and the bills they were set against

Purely additive, and it backfills nothing — there is nothing to backfill.
``ingestion/`` writes both tables from Zoho and a complete re-sync rebuilds
them from nothing, which is what makes them derived state under CLAUDE.md §3
rather than a record only this platform holds.

Neither table is read by any computation. Cost still has exactly one source,
the bill line; see ``VendorCreditDoc`` for why adjusting it is a separate
change that waits on an accounting answer.

Revision ID: 04b3c45610eb
Revises: d1thrv
Create Date: 2026-08-25 03:53:21.383028
"""
from alembic import op
import sqlalchemy as sa


revision = '04b3c45610eb'
down_revision = 'd1thrv'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendor_credits',
    sa.Column('vendor_credit_id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('connector', sa.String(length=32), nullable=True),
    sa.Column('connection_id', sa.String(length=64), nullable=True),
    sa.Column('external_ref', sa.String(length=128), nullable=False),
    sa.Column('number', sa.String(length=128), nullable=True),
    sa.Column('vendor_id', sa.String(length=64), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=48), nullable=False),
    sa.Column('total', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('balance', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('source_ref', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.vendor_id'], ),
    sa.PrimaryKeyConstraint('vendor_credit_id'),
    sa.UniqueConstraint('organization_id', 'connector', 'connection_id', 'external_ref', name='uq_vendor_credit_source')
    )
    with op.batch_alter_table('vendor_credits', schema=None) as batch_op:
        batch_op.create_index('ix_vendor_credit_org_date', ['organization_id', 'date'], unique=False)
        batch_op.create_index(batch_op.f('ix_vendor_credits_connection_id'), ['connection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vendor_credits_connector'), ['connector'], unique=False)
        batch_op.create_index(batch_op.f('ix_vendor_credits_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_vendor_credits_external_ref'), ['external_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_vendor_credits_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vendor_credits_vendor_id'), ['vendor_id'], unique=False)

    op.create_table('vendor_credit_applications',
    sa.Column('vendor_credit_application_id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('connector', sa.String(length=32), nullable=True),
    sa.Column('connection_id', sa.String(length=64), nullable=True),
    sa.Column('external_ref', sa.String(length=128), nullable=False),
    sa.Column('vendor_credit_id', sa.String(length=64), nullable=False),
    sa.Column('vendor_id', sa.String(length=64), nullable=True),
    sa.Column('bill_external_ref', sa.String(length=128), nullable=False),
    sa.Column('bill_number', sa.String(length=128), nullable=True),
    sa.Column('amount_applied', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('source_ref', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['vendor_credit_id'], ['vendor_credits.vendor_credit_id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.vendor_id'], ),
    sa.PrimaryKeyConstraint('vendor_credit_application_id'),
    sa.UniqueConstraint('organization_id', 'connector', 'connection_id', 'external_ref', name='uq_vendor_credit_application_source')
    )
    with op.batch_alter_table('vendor_credit_applications', schema=None) as batch_op:
        batch_op.create_index('ix_vendor_credit_app_org_bill', ['organization_id', 'bill_external_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_vendor_credit_applications_bill_external_ref'), ['bill_external_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_vendor_credit_applications_connection_id'), ['connection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vendor_credit_applications_connector'), ['connector'], unique=False)
        batch_op.create_index(batch_op.f('ix_vendor_credit_applications_external_ref'), ['external_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_vendor_credit_applications_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vendor_credit_applications_vendor_credit_id'), ['vendor_credit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vendor_credit_applications_vendor_id'), ['vendor_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_credit_applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendor_credit_applications_vendor_id'))
        batch_op.drop_index(batch_op.f('ix_vendor_credit_applications_vendor_credit_id'))
        batch_op.drop_index(batch_op.f('ix_vendor_credit_applications_organization_id'))
        batch_op.drop_index(batch_op.f('ix_vendor_credit_applications_external_ref'))
        batch_op.drop_index(batch_op.f('ix_vendor_credit_applications_connector'))
        batch_op.drop_index(batch_op.f('ix_vendor_credit_applications_connection_id'))
        batch_op.drop_index(batch_op.f('ix_vendor_credit_applications_bill_external_ref'))
        batch_op.drop_index('ix_vendor_credit_app_org_bill')

    op.drop_table('vendor_credit_applications')
    with op.batch_alter_table('vendor_credits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendor_credits_vendor_id'))
        batch_op.drop_index(batch_op.f('ix_vendor_credits_organization_id'))
        batch_op.drop_index(batch_op.f('ix_vendor_credits_external_ref'))
        batch_op.drop_index(batch_op.f('ix_vendor_credits_date'))
        batch_op.drop_index(batch_op.f('ix_vendor_credits_connector'))
        batch_op.drop_index(batch_op.f('ix_vendor_credits_connection_id'))
        batch_op.drop_index('ix_vendor_credit_org_date')

    op.drop_table('vendor_credits')
    # ### end Alembic commands ###
