"""locations, and stock per location

Revision ID: 2beaeba8b59c
Revises: b71c4f0a83d5
Create Date: 2026-08-10 22:28:58.078329
"""
from alembic import op
import sqlalchemy as sa


revision = '2beaeba8b59c'
down_revision = 'b71c4f0a83d5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('location_id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('external_ref', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=48), nullable=True),
    sa.Column('parent_external_ref', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('tax_reg_no', sa.String(length=32), nullable=True),
    sa.Column('source_ref', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('location_id'),
    sa.UniqueConstraint('organization_id', 'external_ref', name='uq_location_org_ref')
    )
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_locations_external_ref'), ['external_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_locations_organization_id'), ['organization_id'], unique=False)

    op.create_table('stock_location_snapshots',
    sa.Column('stock_location_snapshot_id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('product_id', sa.String(length=64), nullable=False),
    sa.Column('location_external_ref', sa.String(length=128), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('on_hand', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('available', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('asset_value', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('source_ref', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('stock_location_snapshot_id'),
    sa.UniqueConstraint('organization_id', 'product_id', 'location_external_ref', 'as_of', name='uq_stock_loc_org_product_location_day')
    )
    with op.batch_alter_table('stock_location_snapshots', schema=None) as batch_op:
        batch_op.create_index('ix_stock_loc_org_asof', ['organization_id', 'as_of'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_location_snapshots_as_of'), ['as_of'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_location_snapshots_location_external_ref'), ['location_external_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_location_snapshots_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_location_snapshots_product_id'), ['product_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_location_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_location_snapshots_product_id'))
        batch_op.drop_index(batch_op.f('ix_stock_location_snapshots_organization_id'))
        batch_op.drop_index(batch_op.f('ix_stock_location_snapshots_location_external_ref'))
        batch_op.drop_index(batch_op.f('ix_stock_location_snapshots_as_of'))
        batch_op.drop_index('ix_stock_loc_org_asof')

    op.drop_table('stock_location_snapshots')
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_locations_organization_id'))
        batch_op.drop_index(batch_op.f('ix_locations_external_ref'))

    op.drop_table('locations')
    # ### end Alembic commands ###
