"""credit notes and their applications

Revision ID: 2eab6a5748d7
Revises: c4e7a91d2f38
Create Date: 2026-08-10 20:39:05.683841
"""
from alembic import op
import sqlalchemy as sa


revision = '2eab6a5748d7'
down_revision = 'c4e7a91d2f38'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_notes',
    sa.Column('credit_note_id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('external_ref', sa.String(length=128), nullable=False),
    sa.Column('number', sa.String(length=128), nullable=True),
    sa.Column('customer_id', sa.String(length=64), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=48), nullable=False),
    sa.Column('total', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('balance', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('source_ref', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.PrimaryKeyConstraint('credit_note_id'),
    sa.UniqueConstraint('organization_id', 'external_ref', name='uq_credit_note_org_ref')
    )
    with op.batch_alter_table('credit_notes', schema=None) as batch_op:
        batch_op.create_index('ix_credit_note_org_date', ['organization_id', 'date'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_notes_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_notes_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_notes_external_ref'), ['external_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_notes_organization_id'), ['organization_id'], unique=False)

    op.create_table('credit_note_applications',
    sa.Column('credit_note_application_id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('external_ref', sa.String(length=128), nullable=False),
    sa.Column('credit_note_id', sa.String(length=64), nullable=False),
    sa.Column('customer_id', sa.String(length=64), nullable=True),
    sa.Column('invoice_external_ref', sa.String(length=128), nullable=False),
    sa.Column('invoice_number', sa.String(length=128), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=True),
    sa.Column('applied_on', sa.Date(), nullable=False),
    sa.Column('amount_applied', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('source_ref', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['credit_note_id'], ['credit_notes.credit_note_id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.PrimaryKeyConstraint('credit_note_application_id'),
    sa.UniqueConstraint('organization_id', 'external_ref', name='uq_credit_note_application_org_external')
    )
    with op.batch_alter_table('credit_note_applications', schema=None) as batch_op:
        batch_op.create_index('ix_credit_note_app_org_invoice', ['organization_id', 'invoice_external_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_note_applications_applied_on'), ['applied_on'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_note_applications_credit_note_id'), ['credit_note_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_note_applications_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_note_applications_external_ref'), ['external_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_note_applications_invoice_external_ref'), ['invoice_external_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_note_applications_organization_id'), ['organization_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_note_applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credit_note_applications_organization_id'))
        batch_op.drop_index(batch_op.f('ix_credit_note_applications_invoice_external_ref'))
        batch_op.drop_index(batch_op.f('ix_credit_note_applications_external_ref'))
        batch_op.drop_index(batch_op.f('ix_credit_note_applications_customer_id'))
        batch_op.drop_index(batch_op.f('ix_credit_note_applications_credit_note_id'))
        batch_op.drop_index(batch_op.f('ix_credit_note_applications_applied_on'))
        batch_op.drop_index('ix_credit_note_app_org_invoice')

    op.drop_table('credit_note_applications')
    with op.batch_alter_table('credit_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credit_notes_organization_id'))
        batch_op.drop_index(batch_op.f('ix_credit_notes_external_ref'))
        batch_op.drop_index(batch_op.f('ix_credit_notes_date'))
        batch_op.drop_index(batch_op.f('ix_credit_notes_customer_id'))
        batch_op.drop_index('ix_credit_note_org_date')

    op.drop_table('credit_notes')
    # ### end Alembic commands ###
