"""phase1 decision platform foundation

Revision ID: 41730a334a54
Revises: 
Create Date: 2026-07-25 17:57:50.645981
"""
from alembic import op
import sqlalchemy as sa


revision = '41730a334a54'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cost_records',
    sa.Column('cost_record_id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('external_ref', sa.String(length=160), nullable=False),
    sa.Column('product_id', sa.String(length=64), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('qty', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('source_ref', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('cost_record_id'),
    sa.UniqueConstraint('organization_id', 'external_ref', name='uq_costrecord_org_ref')
    )
    with op.batch_alter_table('cost_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cost_records_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_cost_records_external_ref'), ['external_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_cost_records_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cost_records_product_id'), ['product_id'], unique=False)

    op.create_table('customers',
    sa.Column('customer_id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('assigned_user_id', sa.String(length=64), nullable=True),
    sa.Column('first_seen', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('source_ref', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('customer_id'),
    sa.UniqueConstraint('organization_id', 'external_id', name='uq_customer_org_external')
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customers_assigned_user_id'), ['assigned_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_organization_id'), ['organization_id'], unique=False)

    op.create_table('decisions',
    sa.Column('decision_id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('decision_type', sa.String(length=48), nullable=False),
    sa.Column('decision_key', sa.String(length=128), nullable=False),
    sa.Column('subject_entity_type', sa.String(length=32), nullable=False),
    sa.Column('subject_entity_id', sa.String(length=64), nullable=False),
    sa.Column('assigned_user_id', sa.String(length=64), nullable=True),
    sa.Column('assigned_role', sa.String(length=32), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('signal_ids', sa.JSON(), nullable=False),
    sa.Column('evidence_refs', sa.JSON(), nullable=False),
    sa.Column('ai', sa.JSON(), nullable=False),
    sa.Column('priority_band', sa.String(length=16), nullable=False),
    sa.Column('priority_score', sa.Integer(), nullable=False),
    sa.Column('priority_deterministic_base', sa.Integer(), nullable=False),
    sa.Column('priority_ai_adjustment', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('human_action', sa.JSON(), nullable=True),
    sa.Column('override_reason', sa.String(length=1024), nullable=True),
    sa.Column('outcome_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('decision_id'),
    sa.UniqueConstraint('decision_key', name='uq_decision_key')
    )
    with op.batch_alter_table('decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_decisions_assigned_user_id'), ['assigned_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_decisions_decision_key'), ['decision_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_decisions_decision_type'), ['decision_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_decisions_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_decisions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_decisions_subject_entity_id'), ['subject_entity_id'], unique=False)

    op.create_table('organizations',
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('erp', sa.String(length=32), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('organization_id')
    )
    op.create_table('products',
    sa.Column('product_id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('uom', sa.String(length=32), nullable=True),
    sa.Column('hsn', sa.String(length=32), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('source_ref', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('product_id'),
    sa.UniqueConstraint('organization_id', 'external_id', name='uq_product_org_external')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_organization_id'), ['organization_id'], unique=False)

    op.create_table('quote_drafts',
    sa.Column('quote_id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('customer_id', sa.String(length=64), nullable=False),
    sa.Column('salesperson_id', sa.String(length=64), nullable=True),
    sa.Column('lines', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('quote_id')
    )
    with op.batch_alter_table('quote_drafts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quote_drafts_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quote_drafts_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quote_drafts_salesperson_id'), ['salesperson_id'], unique=False)

    op.create_table('sales_txns',
    sa.Column('sales_txn_id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('external_ref', sa.String(length=160), nullable=False),
    sa.Column('customer_id', sa.String(length=64), nullable=False),
    sa.Column('product_id', sa.String(length=64), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('qty', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('line_revenue', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('source_ref', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('sales_txn_id'),
    sa.UniqueConstraint('organization_id', 'external_ref', name='uq_salestxn_org_ref')
    )
    with op.batch_alter_table('sales_txns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_txns_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_txns_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_txns_external_ref'), ['external_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_txns_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_txns_product_id'), ['product_id'], unique=False)

    op.create_table('signals',
    sa.Column('signal_id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('signal_type', sa.String(length=48), nullable=False),
    sa.Column('subject_entity_type', sa.String(length=32), nullable=False),
    sa.Column('subject_entity_id', sa.String(length=64), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('detector_version', sa.String(length=32), nullable=False),
    sa.Column('threshold_config_version', sa.String(length=32), nullable=False),
    sa.Column('window', sa.JSON(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('severity_base', sa.Integer(), nullable=False),
    sa.Column('evidence_refs', sa.JSON(), nullable=False),
    sa.Column('sufficiency', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('signal_id')
    )
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signals_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_signals_signal_type'), ['signal_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_signals_subject_entity_id'), ['subject_entity_id'], unique=False)

    op.create_table('outcomes',
    sa.Column('outcome_id', sa.String(length=64), nullable=False),
    sa.Column('decision_id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('human_action_summary', sa.String(length=1024), nullable=True),
    sa.Column('measurement_window', sa.JSON(), nullable=False),
    sa.Column('measured_metrics', sa.JSON(), nullable=False),
    sa.Column('impact', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.decision_id'], ),
    sa.PrimaryKeyConstraint('outcome_id')
    )
    with op.batch_alter_table('outcomes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outcomes_decision_id'), ['decision_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_outcomes_organization_id'), ['organization_id'], unique=False)

    op.create_table('users',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.organization_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_organization_id'), ['organization_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_organization_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('outcomes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outcomes_organization_id'))
        batch_op.drop_index(batch_op.f('ix_outcomes_decision_id'))

    op.drop_table('outcomes')
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signals_subject_entity_id'))
        batch_op.drop_index(batch_op.f('ix_signals_signal_type'))
        batch_op.drop_index(batch_op.f('ix_signals_organization_id'))

    op.drop_table('signals')
    with op.batch_alter_table('sales_txns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_txns_product_id'))
        batch_op.drop_index(batch_op.f('ix_sales_txns_organization_id'))
        batch_op.drop_index(batch_op.f('ix_sales_txns_external_ref'))
        batch_op.drop_index(batch_op.f('ix_sales_txns_date'))
        batch_op.drop_index(batch_op.f('ix_sales_txns_customer_id'))

    op.drop_table('sales_txns')
    with op.batch_alter_table('quote_drafts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quote_drafts_salesperson_id'))
        batch_op.drop_index(batch_op.f('ix_quote_drafts_organization_id'))
        batch_op.drop_index(batch_op.f('ix_quote_drafts_customer_id'))

    op.drop_table('quote_drafts')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_organization_id'))
        batch_op.drop_index(batch_op.f('ix_products_external_id'))

    op.drop_table('products')
    op.drop_table('organizations')
    with op.batch_alter_table('decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_decisions_subject_entity_id'))
        batch_op.drop_index(batch_op.f('ix_decisions_status'))
        batch_op.drop_index(batch_op.f('ix_decisions_organization_id'))
        batch_op.drop_index(batch_op.f('ix_decisions_decision_type'))
        batch_op.drop_index(batch_op.f('ix_decisions_decision_key'))
        batch_op.drop_index(batch_op.f('ix_decisions_assigned_user_id'))

    op.drop_table('decisions')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_organization_id'))
        batch_op.drop_index(batch_op.f('ix_customers_external_id'))
        batch_op.drop_index(batch_op.f('ix_customers_assigned_user_id'))

    op.drop_table('customers')
    with op.batch_alter_table('cost_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cost_records_product_id'))
        batch_op.drop_index(batch_op.f('ix_cost_records_organization_id'))
        batch_op.drop_index(batch_op.f('ix_cost_records_external_ref'))
        batch_op.drop_index(batch_op.f('ix_cost_records_date'))

    op.drop_table('cost_records')
    # ### end Alembic commands ###
