"""quote decision records the catalogue ruleset that resolved it

Which pie-parser catalogue produced the product on a priced line. Distinct from
`engine_version`, which names the quote-intelligence engine; this is the
parser's own ruleset checksum, derived from the price-file bytes plus the pack.

Decisions written before this column existed genuinely do not know their
catalogue, and empty says exactly that. It is not a default that will be
mistaken for a real checksum, and backfilling one would be inventing provenance
for rows whose provenance was never captured.

Revision ID: 65139e67e76d
Revises: b3e91d7a4c26
Create Date: 2026-08-07 04:41:04.086247
"""
from alembic import op
import sqlalchemy as sa


revision = '65139e67e76d'
down_revision = 'b3e91d7a4c26'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # server_default is required, not cosmetic: the column is NOT NULL and this
    # table has rows in every deployment that has ever priced a quote, so the
    # autogenerated version without it fails on exactly the databases that
    # matter.
    with op.batch_alter_table('quote_decisions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('catalog_version', sa.String(length=64),
                                      nullable=False, server_default=''))


def downgrade() -> None:
    with op.batch_alter_table('quote_decisions', schema=None) as batch_op:
        batch_op.drop_column('catalog_version')
