"""Every imported record carries where it came from.

Customers, products and vendors were keyed on ``(organization_id,
external_id)``. That is unique only by accident: Zoho issues globally unique
contact and item ids, so two connected Zoho companies never collided. The first
connector that numbers records per company — Tally numbers ledgers from 1 —
breaks it, and breaks it *silently*: two different customers upsert onto one
row and one of them disappears.

An imported record's identity is (connector, connected company, the id that
system gave it). Never its name: "ABC Industries" can legitimately exist in
three connected companies and be three different customers.

``connector`` and ``connection_id`` are **nullable**, and nothing is
backfilled. A row imported before this existed cannot be attributed after the
fact — the sync run that wrote it did not record which connection it came from
— and picking the organization's only connection would be inventing provenance
that happens to be right today and wrong the moment a second company connects.
NULL reads as "source not recorded", which is the true statement, and the next
full sync attributes the rows it re-reads.

The unique constraint is replaced rather than added alongside: two constraints
where one is a strict subset of the other means the narrow one still rejects
the writes the wide one was added to permit.

SQLite cannot drop a constraint in place, so this runs inside
``batch_alter_table``, which rebuilds the table. On Postgres the same calls are
plain DDL.

Revision ID: a8d5e21b6f47
Revises: f3a71c9e05b2
Create Date: 2026-08-05
"""
from alembic import op
import sqlalchemy as sa

revision = "a8d5e21b6f47"
down_revision = "f3a71c9e05b2"
branch_labels = None
depends_on = None

#: table, old constraint, new constraint
_TABLES = (
    ("customers", "uq_customer_org_external", "uq_customer_source"),
    ("products", "uq_product_org_external", "uq_product_source"),
    ("vendors", "uq_vendor_org_external", "uq_vendor_source"),
)


def upgrade() -> None:
    for table, old, new in _TABLES:
        with op.batch_alter_table(table) as batch:
            batch.add_column(sa.Column("connector", sa.String(32), nullable=True))
            batch.add_column(sa.Column("connection_id", sa.String(64), nullable=True))
            # Named constraints throughout, so this drop finds its target on
            # every backend rather than only where the name was autogenerated.
            batch.drop_constraint(old, type_="unique")
            batch.create_unique_constraint(
                new, ["organization_id", "connector", "connection_id", "external_id"])
        op.create_index(f"ix_{table}_connector", table, ["connector"])
        op.create_index(f"ix_{table}_connection_id", table, ["connection_id"])


def downgrade() -> None:
    for table, old, new in _TABLES:
        op.drop_index(f"ix_{table}_connection_id", table_name=table)
        op.drop_index(f"ix_{table}_connector", table_name=table)
        with op.batch_alter_table(table) as batch:
            batch.drop_constraint(new, type_="unique")
            batch.create_unique_constraint(old, ["organization_id", "external_id"])
            batch.drop_column("connection_id")
            batch.drop_column("connector")
