"""Trust controls: per-tenant keys, name vault, break-glass access, payload log.

Six new tables, no changes to existing ones. Written by hand rather than
autogenerated: on this schema ``--autogenerate`` also emits several hundred
nullability and index rewrites across every existing table, which are artefacts
of SQLite reflection rather than real drift, and shipping them would rebuild
tables this change has no business touching.

Revision ID: b4e17d90c3aa
Revises: a7c02f5b8e14
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "b4e17d90c3aa"
down_revision = "a7c02f5b8e14"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "tenant_keys",
        sa.Column("organization_id", sa.String(64), primary_key=True),
        sa.Column("wrapped_dek", sa.Text(), nullable=False, server_default=""),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("destroyed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("destroyed_by_user_id", sa.String(64), nullable=True),
        sa.Column("destroy_reason", sa.String(512), nullable=True),
    )

    op.create_table(
        "name_vault",
        sa.Column("entry_id", sa.String(64), primary_key=True),
        sa.Column("organization_id", sa.String(64), nullable=False),
        sa.Column("entity_type", sa.String(16), nullable=False),
        sa.Column("entity_id", sa.String(64), nullable=False),
        sa.Column("name_ciphertext", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.UniqueConstraint("organization_id", "entity_type", "entity_id",
                            name="uq_name_vault_entity"),
    )
    op.create_index("ix_name_vault_organization_id", "name_vault", ["organization_id"])
    op.create_index("ix_name_vault_entity_type", "name_vault", ["entity_type"])
    op.create_index("ix_name_vault_entity_id", "name_vault", ["entity_id"])

    op.create_table(
        "access_grants",
        sa.Column("grant_id", sa.String(64), primary_key=True),
        sa.Column("organization_id", sa.String(64), nullable=False),
        sa.Column("staff_user_id", sa.String(64), nullable=False),
        sa.Column("justification", sa.String(1024), nullable=False),
        sa.Column("granted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index("ix_access_grants_organization_id", "access_grants", ["organization_id"])
    op.create_index("ix_access_grants_staff_user_id", "access_grants", ["staff_user_id"])
    op.create_index("ix_access_grants_granted_at", "access_grants", ["granted_at"])
    op.create_index("ix_access_grants_expires_at", "access_grants", ["expires_at"])

    op.create_table(
        "access_events",
        sa.Column("event_id", sa.String(64), primary_key=True),
        sa.Column("organization_id", sa.String(64), nullable=False),
        sa.Column("access_grant_id", sa.String(64), nullable=False),
        sa.Column("staff_user_id", sa.String(64), nullable=False),
        sa.Column("action", sa.String(16), nullable=False),
        sa.Column("detail", sa.String(512), nullable=False, server_default=""),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index("ix_access_events_organization_id", "access_events", ["organization_id"])
    op.create_index("ix_access_events_access_grant_id", "access_events", ["access_grant_id"])
    op.create_index("ix_access_events_staff_user_id", "access_events", ["staff_user_id"])
    op.create_index("ix_access_events_action", "access_events", ["action"])
    op.create_index("ix_access_events_created_at", "access_events", ["created_at"])

    op.create_table(
        "model_payloads",
        sa.Column("payload_id", sa.String(64), primary_key=True),
        sa.Column("organization_id", sa.String(64), nullable=False),
        sa.Column("ai_call_log_id", sa.String(64), nullable=True),
        sa.Column("decision_type", sa.String(48), nullable=False, server_default=""),
        sa.Column("provider", sa.String(32), nullable=False, server_default=""),
        sa.Column("model", sa.String(64), nullable=False, server_default=""),
        sa.Column("payload_ciphertext", sa.Text(), nullable=False),
        sa.Column("disclosure_findings", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index("ix_model_payloads_organization_id", "model_payloads", ["organization_id"])
    op.create_index("ix_model_payloads_ai_call_log_id", "model_payloads", ["ai_call_log_id"])
    op.create_index("ix_model_payloads_created_at", "model_payloads", ["created_at"])

    op.create_table(
        "erasure_receipts",
        sa.Column("receipt_id", sa.String(64), primary_key=True),
        sa.Column("organization_id", sa.String(64), nullable=False),
        sa.Column("manifest", sa.JSON(), nullable=False),
        sa.Column("reason", sa.String(512), nullable=False, server_default=""),
        sa.Column("actor_user_id", sa.String(64), nullable=True),
        sa.Column("erased_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("signature", sa.String(128), nullable=False, server_default=""),
    )
    op.create_index("ix_erasure_receipts_organization_id", "erasure_receipts",
                    ["organization_id"])
    op.create_index("ix_erasure_receipts_erased_at", "erasure_receipts", ["erased_at"])


def downgrade() -> None:
    op.drop_table("erasure_receipts")
    op.drop_table("model_payloads")
    op.drop_table("access_events")
    op.drop_table("access_grants")
    op.drop_table("name_vault")
    op.drop_table("tenant_keys")
