"""Supply, stock and cash: vendors, stock snapshots, payments, purchase orders

Purely additive: five new tables and their indexes, no change to any existing
one. Nothing here can fail on a populated database, and a rollback drops only
tables this revision created.

Written out literally rather than from the models, per the rule that a
migration must run against a schema from months ago while the models describe
today.

Revision ID: cca6781337ea
Revises: c8f5a1e73b29
Create Date: 2026-08-05 03:31:45.080866
"""
from alembic import op
import sqlalchemy as sa


revision = 'cca6781337ea'
down_revision = 'c8f5a1e73b29'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendors',
    sa.Column('vendor_id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('gstin', sa.String(length=32), nullable=True),
    sa.Column('pan', sa.String(length=32), nullable=True),
    sa.Column('payment_terms_days', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('source_ref', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('vendor_id'),
    sa.UniqueConstraint('organization_id', 'external_id', name='uq_vendor_org_external')
    )
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vendors_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vendors_gstin'), ['gstin'], unique=False)
        batch_op.create_index(batch_op.f('ix_vendors_organization_id'), ['organization_id'], unique=False)

    op.create_table('payment_receipts',
    sa.Column('payment_receipt_id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('external_ref', sa.String(length=128), nullable=False),
    sa.Column('customer_id', sa.String(length=64), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('mode', sa.String(length=64), nullable=True),
    sa.Column('is_advance', sa.Boolean(), nullable=False),
    sa.Column('unapplied_amount', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('source_ref', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.PrimaryKeyConstraint('payment_receipt_id'),
    sa.UniqueConstraint('organization_id', 'external_ref', name='uq_payment_org_external')
    )
    with op.batch_alter_table('payment_receipts', schema=None) as batch_op:
        batch_op.create_index('ix_payment_org_date', ['organization_id', 'date'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_receipts_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_receipts_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_receipts_external_ref'), ['external_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_receipts_organization_id'), ['organization_id'], unique=False)

    op.create_table('purchase_orders',
    sa.Column('purchase_order_id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('external_ref', sa.String(length=128), nullable=False),
    sa.Column('number', sa.String(length=128), nullable=True),
    sa.Column('vendor_id', sa.String(length=64), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('expected_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=48), nullable=False),
    sa.Column('received_status', sa.String(length=48), nullable=True),
    sa.Column('ordered_qty', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('pending_qty', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('total', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('received_on', sa.Date(), nullable=True),
    sa.Column('source_ref', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.vendor_id'], ),
    sa.PrimaryKeyConstraint('purchase_order_id'),
    sa.UniqueConstraint('organization_id', 'external_ref', name='uq_purchase_order_org_external')
    )
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.create_index('ix_po_org_date', ['organization_id', 'date'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_orders_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_orders_external_ref'), ['external_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_orders_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_orders_vendor_id'), ['vendor_id'], unique=False)

    op.create_table('stock_snapshots',
    sa.Column('stock_snapshot_id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('product_id', sa.String(length=64), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('on_hand', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('available', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('actual_available', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('reorder_level', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('purchase_rate', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('tracked', sa.Boolean(), nullable=False),
    sa.Column('source_ref', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('stock_snapshot_id'),
    sa.UniqueConstraint('organization_id', 'product_id', 'as_of', name='uq_stock_org_product_day')
    )
    with op.batch_alter_table('stock_snapshots', schema=None) as batch_op:
        batch_op.create_index('ix_stock_org_asof', ['organization_id', 'as_of'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_snapshots_as_of'), ['as_of'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_snapshots_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_snapshots_product_id'), ['product_id'], unique=False)

    op.create_table('payment_applications',
    sa.Column('payment_application_id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('external_ref', sa.String(length=128), nullable=False),
    sa.Column('payment_receipt_id', sa.String(length=64), nullable=False),
    sa.Column('customer_id', sa.String(length=64), nullable=False),
    sa.Column('invoice_external_ref', sa.String(length=128), nullable=False),
    sa.Column('invoice_number', sa.String(length=128), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('invoice_due_date', sa.Date(), nullable=True),
    sa.Column('paid_on', sa.Date(), nullable=False),
    sa.Column('amount_applied', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('source_ref', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.ForeignKeyConstraint(['payment_receipt_id'], ['payment_receipts.payment_receipt_id'], ),
    sa.PrimaryKeyConstraint('payment_application_id'),
    sa.UniqueConstraint('organization_id', 'external_ref', name='uq_payment_application_org_external')
    )
    with op.batch_alter_table('payment_applications', schema=None) as batch_op:
        batch_op.create_index('ix_payment_app_org_invoice', ['organization_id', 'invoice_external_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_applications_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_applications_external_ref'), ['external_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_applications_invoice_external_ref'), ['invoice_external_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_applications_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_applications_paid_on'), ['paid_on'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_applications_payment_receipt_id'), ['payment_receipt_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_applications_payment_receipt_id'))
        batch_op.drop_index(batch_op.f('ix_payment_applications_paid_on'))
        batch_op.drop_index(batch_op.f('ix_payment_applications_organization_id'))
        batch_op.drop_index(batch_op.f('ix_payment_applications_invoice_external_ref'))
        batch_op.drop_index(batch_op.f('ix_payment_applications_external_ref'))
        batch_op.drop_index(batch_op.f('ix_payment_applications_customer_id'))
        batch_op.drop_index('ix_payment_app_org_invoice')

    op.drop_table('payment_applications')
    with op.batch_alter_table('stock_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_snapshots_product_id'))
        batch_op.drop_index(batch_op.f('ix_stock_snapshots_organization_id'))
        batch_op.drop_index(batch_op.f('ix_stock_snapshots_as_of'))
        batch_op.drop_index('ix_stock_org_asof')

    op.drop_table('stock_snapshots')
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_orders_vendor_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_orders_organization_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_orders_external_ref'))
        batch_op.drop_index(batch_op.f('ix_purchase_orders_date'))
        batch_op.drop_index('ix_po_org_date')

    op.drop_table('purchase_orders')
    with op.batch_alter_table('payment_receipts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_receipts_organization_id'))
        batch_op.drop_index(batch_op.f('ix_payment_receipts_external_ref'))
        batch_op.drop_index(batch_op.f('ix_payment_receipts_date'))
        batch_op.drop_index(batch_op.f('ix_payment_receipts_customer_id'))
        batch_op.drop_index('ix_payment_org_date')

    op.drop_table('payment_receipts')
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendors_organization_id'))
        batch_op.drop_index(batch_op.f('ix_vendors_gstin'))
        batch_op.drop_index(batch_op.f('ix_vendors_external_id'))

    op.drop_table('vendors')
    # ### end Alembic commands ###
