"""Qualify a recorded outcome's ERP pointer by the company it belongs to.

``quote_outcomes.quote_document_ref`` names a quote in an ERP, and an ERP
reference is unique only inside the book that issued it. The constraint was
``(organization_id, quote_document_ref)``, which is unique only by accident:
Zoho's estimate ids are system-wide, so three connected Zoho books never
collided. The connectors in ``ingestion/erp`` read systems whose quote numbers
are per-company sequences — Business Central's ``SQ-1001``, Acumatica's
``QT000123`` — and two connected books of one of those issue the same
reference twice. Unqualified, the second book's outcome could not be recorded
at all: the constraint refused it as a duplicate of a quote it has nothing to
do with.

The constraint is **replaced** rather than added alongside. Two constraints
where one is a strict subset of the other means the narrow one still rejects
the writes the wide one was added to permit — the reasoning
``a8d5e21b6f47_entity_source_identity`` states for the master tables, applied
to the one pointer that still lacked it.

**RISK — this drops a unique constraint.** No existing row is refused by the
new one: it is strictly wider, and a NULL company is distinct from every other
NULL under SQL's unique semantics on both SQLite and PostgreSQL. What it no
longer refuses is two *company-less* rows naming one reference, which the
constraint used to catch and ``quote_service.set_outcome``'s own guard now
does — a domain refusal with a sentence, rather than an IntegrityError at
commit. Verified on an empty database and on the PostgreSQL sandbox, both of
which the gate already runs.

SQLite cannot drop a constraint in place, so this runs inside
``batch_alter_table``, which rebuilds the table. On PostgreSQL the same calls
are plain DDL.

Revision ID: w10qptr
Revises: v9qrev
Create Date: 2026-09-21
"""
from alembic import op

revision = "w10qptr"
down_revision = "v9qrev"
branch_labels = None
depends_on = None

_NAME = "uq_quote_outcome_org_document"


def upgrade() -> None:
    with op.batch_alter_table("quote_outcomes") as batch:
        # Named throughout, so the drop finds its target on every backend
        # rather than only where the name was autogenerated.
        batch.drop_constraint(_NAME, type_="unique")
        batch.create_unique_constraint(
            _NAME, ["organization_id", "quote_document_connection_id",
                    "quote_document_ref"])


def downgrade() -> None:
    with op.batch_alter_table("quote_outcomes") as batch:
        batch.drop_constraint(_NAME, type_="unique")
        batch.create_unique_constraint(
            _NAME, ["organization_id", "quote_document_ref"])
